[stress]
bursts_per_loop_min = [8,8,8,8]
bursts_per_loop_incr = 0
mutations_per_burst_min = [8,8,8,8]
mutations_per_burst_incr = 0
request_delay = 0.2
burst_delay = 2
loop_delay = 20
loop_count = 2
measurement_delay = 0.5
wait_for_bursts_to_complete = true
payload_path = "payload/light.graphql"
