[stress]
bursts_per_loop_min=3
bursts_per_loop_incr=2
requests_per_burst_min=20
requests_per_burst_incr=10
request_delay=0.1
burst_delay=6
loop_delay=30
loop_count=4
measurement_delay=0.5
wait_for_bursts_to_complete=false
payload_path="payload/light.graphql"
