[stress]
bursts_per_loop_min=20
bursts_per_loop_incr=10
mutations_per_burst_min=10
mutations_per_burst_incr=0
request_delay=0.5
burst_delay=0.5
loop_delay=30
loop_count=10
measurement_delay=0.5
wait_for_bursts_to_complete=true
payload_path="payload/light.graphql"
